### ISSUE TITLE
Installation scripts referenced in the Sunbird documentation must have test cases

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/sunbird-devops#10]
None of the deployment scripts present in this directory https://github.com/project-sunbird/sunbird-devops/tree/master/deploy have any test cases. Thus it's impossible to know if the scripts are broken or if there is an error to be found.

If we are recommending that a new adopter of Sunbird use automation to bootstrap a new Sunbird instance, the automation must be tested thoroughly.

**Comment by kochhar** [comment]
Examples: 
- https://github.com/project-sunbird/sunbird-commons/issues/110
- https://github.com/project-sunbird/sunbird-commons/issues/69#issuecomment-337456705

**Comment by kochhar** [comment]
And another:
https://github.com/project-sunbird/sunbird-commons/issues/111

**Comment by rjshrjndrn** [comment]
Closing as idle issue. Feel free to reopen.
