### ISSUE TITLE
Installation scripts for Sunbird installation must be idempotent

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/sunbird-devops#11]
Current db initialisation script is not idempotent -- this means that the DB initialisation code cannot be run multiple times to correct errors. This is causing problems for installers because the database configuration cannot be automated. 

See: https://github.com/project-sunbird/sunbird-commons/issues/111#issuecomment-343912528

**Comment by SMYALTAMASH** [comment]
This activity is completed.
