### ISSUE TITLE
API access to Sunbird Adopter 

### ISSUE THREAD

**Issue by ahghatol** [project-sunbird/sunbird-devops#153]
As of now, the integration partner group have access to groups
  - echoUser   
  - orgAdmin 
  - orgUpdate
  - orgUser
  - userAdmin
  - userUpdate
  - publicUser
  - dataAdmin
  - dataUpdate
  - domainAdmin
  - domainUpdate
  - domainUser
  - dialcodeAdmin
  - dialcodeUpdate
  - appAdmin

And they don't have access to following groups
 -  appUpdate 
 -   noteUser
 -   configUser
 -  noteUpdate
 -  noteAdmin
 -  mobileApp
 - mobileAdmin
 - courseUser
 - courseUpdate
 - courseAdmin
 - contentAdmin
 - contentUpdate
 - contentUser

[Groups and API access document link](https://docs.google.com/spreadsheets/d/1O2QADGzizOClGRjmx_1JVGAHoXwDNY7GDsEtnO3nnpI/edit#gid=772094723)

**Comment by SMYALTAMASH** [comment]
This activity is completed.
