### ISSUE TITLE
Artifact Download 404 error from Blob

### ISSUE THREAD

**Issue by saibhargav29-git** [project-sunbird/sunbird-devops#1946]
Hi,

Facing error while downloading artifacts from Blob in azure ubuntu 16.04 core vm as it saying blob doesnt exist so the install.sh failing 

artifacts="cassandra_artifacts.zip v3.zip content-plugins.zip formdata.zip keycloak_artifacts.zip" 

****/home/azureuser/sunbird-devops/private_repo/ansible/inventory/dev
downloading artifacts
--2020-09-29 05:26:42--  https://sunbirdpublic.blob.core.windows.net/installation/2.6.0/Core/cassandra_artifacts.zip
Resolving sunbirdpublic.blob.core.windows.net (sunbirdpublic.blob.core.windows.net)... 104.211.109.52
Connecting to sunbirdpublic.blob.core.windows.net (sunbirdpublic.blob.core.windows.net)|104.211.109.52|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist****

**Comment by rjshrjndrn** [comment]
We no more support minimal installation. So closing this ticket.
