### ISSUE TITLE
Subird Installation on AWS throws error

### ISSUE THREAD

**Issue by saibhargav29-git** [project-sunbird/sunbird-devops#1947]
Hi,

Not able to install Subird minimal on Aws ubuntu core vm 16.04 so please look at the below screenshot

++ kp_ip=172.31.95.174
++ domain_name=sunbird.centralindia.cloudapp.azure.com
++ storage_account_name=3node
++ storage_container_name=content
++ azure_storage_key=MdOxjlgOzlSFPHKM+XcdnxcVEnd6cbZT7J3oSN9+TjXQB+bZpex2ZUZkAyfOfi/UFP2/PZQfPzghph0gxcIGGg==
++ create_ssl=true
++ nginx_cert_path=/home/ubuntu/site.crt
++ nginx_key_path=/home/ubuntu/site.key
++ ssh_user=ops
++ version=2.6.0
+ echo set 0400 for keyfile
+ [[ -f /home/ubuntu/deployer.pem ]]
+ chmod 0400 /home/ubuntu/deployer.pem
set 0400 for keyfile
+ mkdir -p /home/ubuntu/.config/sunbird
+ [[ -f /home/ubuntu/.config/sunbird/certbot ]]
+ [[ true == \t\r\u\e ]]
+ echo 'Creating' SSL 'certificate.'
Creating SSL certificate.
+ bash certbot.sh
#### Creating SSL Certificates ####

This script won't work for aws, as it's black listed in letsencrypt
so if youre running on aws please press ctrl+c with in 5 seconds

**Comment by rjshrjndrn** [comment]
As it's noted, fqdn  provided by aws won't work for letsencrypt. So please use another domain or keep your own ssl certs.
