### ISSUE TITLE
sunbird_install.sh fails with Incorrect sudo password message

### ISSUE THREAD

**Issue by VaibhavSavla** [project-sunbird/sunbird-devops#215]
Hello,

I am a part of the Bodhi team working on Lex. I am trying to install Sunbird 1.8.1 using the following guide http://www.sunbird.org/developer-docs/installation/server_installation/ on 2 ec2 servers.
I have created a user 'sbuser' on both servers and keyed ssh is enabled for both servers. I modified the config file with the appropriate values
When I try to run the sunbird_install.sh. It fails with the message Incorrect sudo password. I have checked the inventories file and the password there is correct.

Also afterwards when I try to login with that user I get access denied.

**Comment by SMYALTAMASH** [comment]
This is invalid with latest release.
