### ISSUE TITLE
Installing sunbird on AWS

### ISSUE THREAD

**Issue by ashisharora111** [project-sunbird/sunbird-devops#2213]
Has anyone installed Sunbird 3.5.0 on AWS? 

If yes, I need help on ansible variables setup, updating common.yml, hosts, secrets.yml under Core, KnowledgePlatform and DataPipeline.

**Comment by rjshrjndrn** [comment]
Hi please raise questions regarding the installation at our community discussions forum. https://github.com/project-sunbird/sunbird-community/discussions/categories/-20-sunbird-installation-and-configuration
