### ISSUE TITLE
Sunbird Install script fails to setup Kong. 

### ISSUE THREAD

**Issue by manish-nineleaps** [project-sunbird/sunbird-devops#223]
I am following the Sunbird server documentation but it looks like there is an issue with Kong setup. 
It fails to come up and the deploy script dies ( ubuntu 16.04 LTS)

Trace:
@@@@@@@@@ Deploy Admin Utils API
 [WARNING]: While constructing a mapping from /home/ubuntu/sunbird-devops/ansible/roles/stack-sunbird/defaults/main.yml, line 2, column 1, found a duplicate dict key
(sunbird_env_logo_url). Using last defined value only.

PLAY [swarm-bootstrap-manager] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [172.31.30.26]

PLAY [swarm-bootstrap-manager] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [172.31.30.26]

PLAY [swarm-bootstrap-manager] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [172.31.30.26]

PLAY [swarm-bootstrap-manager] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [172.31.30.26]

TASK [stack-adminutil : Ensure env directory exists] *****************************************************************************************************************************
ok: [172.31.30.26]

TASK [stack-adminutil : Ensure stack directory exists] ***************************************************************************************************************************
ok: [172.31.30.26]

TASK [stack-adminutil : Save stack file] *****************************************************************************************************************************************
changed: [172.31.30.26]

TASK [stack-adminutil : Deploy stack] ********************************************************************************************************************************************
changed: [172.31.30.26]

PLAY [swarm-bootstrap-manager] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [172.31.30.26]

PLAY [swarm-bootstrap-manager] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [172.31.30.26]

PLAY [swarm-bootstrap-manager] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [172.31.30.26]

PLAY RECAP ***********************************************************************************************************************************************************************
172.31.30.26               : ok=11   changed=2    unreachable=0    failed=0

api-manager kong container is not running, waiting for 5 more seconds, retying 5
api-manager kong container is not running, waiting for 5 more seconds, retying 4
api-manager kong container is not running, waiting for 5 more seconds, retying 3
@@@@@@@@@ Onboard APIs
 [WARNING]: While constructing a mapping from /home/ubuntu/sunbird-devops/ansible/roles/kong-api/defaults/main.yml, line 3035, column 7, found a duplicate dict key
(config.allowed_payload_size). Using last defined value only.

 [WARNING]: While constructing a mapping from /home/ubuntu/sunbird-devops/ansible/roles/kong-api/defaults/main.yml, line 3052, column 7, found a duplicate dict key
(config.allowed_payload_size). Using last defined value only.

PLAY [Kong API] ******************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [localhost]

TASK [kong-api : Ensure pip is installed] ****************************************************************************************************************************************
ok: [localhost]

TASK [kong-api : Ensure retry is installed] **************************************************************************************************************************************
changed: [localhost]

TASK [kong-api : Save api details to json file] **********************************************************************************************************************************
changed: [localhost]

TASK [kong-api : Copy kong api scripts] ******************************************************************************************************************************************
changed: [localhost]

TASK [kong-api : Ensure kong_admin_api_url is available before running the scripts] **********************************************************************************************
FAILED - RETRYING: Ensure kong_admin_api_url is available before running the scripts (60 retries left).
........ ( it tries 60 times and fails)

**Comment by manish-nineleaps** [comment]
On inspecting this further, it looks like that the Kong container is not able to talk to PostgreSQL installed on the bare box. Trace:

api-manager_kong.1.zq5vhn7vxott@ip-172-31-30-26    | KONG_CLUSTER_LISTEN: 10.0.2.76:7946
api-manager_kong.1.zboq23jkf282@ip-172-31-30-26    | KONG_CLUSTER_LISTEN: 10.0.2.45:7946
api-manager_kong.1.zq5vhn7vxott@ip-172-31-30-26    | Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: [postgres error] closed
api-manager_kong.1.zboq23jkf282@ip-172-31-30-26    | Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: [postgres error] closed
api-manager_kong.1.zq5vhn7vxott@ip-172-31-30-26    |
api-manager_kong.1.zq5vhn7vxott@ip-172-31-30-26    |   Run with --v (verbose) or --vv (debug) for more details
api-manager_kong.1.zboq23jkf282@ip-172-31-30-26    |
api-manager_kong.1.zboq23jkf282@ip-172-31-30-26    |   Run with --v (verbose) or --vv (debug) for more details
api-manager_kong.1.zepiwdmuyc44@ip-172-31-30-26    | KONG_CLUSTER_LISTEN: 10.0.2.33:7946
api-manager_kong.1.zepiwdmuyc44@ip-172-31-30-26    | Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: [postgres error] closed
api-manager_kong.1.zepiwdmuyc44@ip-172-31-30-26    |
api-manager_kong.1.zepiwdmuyc44@ip-172-31-30-26    |   Run with --v (verbose) or --vv (debug) for more details
api-manager_kong.1.zp6wm3cv25hs@ip-172-31-30-26    | KONG_CLUSTER_LISTEN: 10.0.2.58:7946
api-manager_kong.1.zp6wm3cv25hs@ip-172-31-30-26    | Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:18: [postgres error] closed
api-manager_kong.1.zp6wm3cv25hs@ip-172-31-30-26    |
api-manager_kong.1.zp6wm3cv25hs@ip-172-31-30-26    |   Run with --v (verbose) or --vv (debug) for more details
api-manager_kong.1.oaw0gbvdto9h@ip-172-31-30-26    | KONG_CLUSTER_LISTEN: 10.0.2.91:7946

**Comment by rjshrjndrn** [comment]
Closing the issue, due to inactivity
