### ISSUE TITLE
Getting error in AdminUtils, Learner and LMS.

### ISSUE THREAD

**Issue by tsheth** [project-sunbird/sunbird-devops#2236]
3 Jenkins pipelines are failing to decrypt credentials...

sunbird-devops/kubernetes/ansible/roles/mount-keys/tasks/decrypt.yml

Task [mount-keys: Decrypt the data first]**********************************************
field: [localhost] (item=1) => {
"changed" = true,
"cmd": "ansible-vault decrypt [] --vault-password-file /var/lib/jenkins/secrets/vault-pass",
***
***
***
}

STDERR: 
ERROR! [Errno 2] No Such file or directory:
u'/var/lib/jenkins/workspace/Deploy/dev/Kubernetes/lms/kubernetes/ansible/[]'

Key folder is not available in workspace/Deploy/dev/kubernetes/AdminUtils/ansible/inventory/env location

**Comment by keshavprasadms** [comment]
Please raise issues in the sunbird community going forward for any installation issues. To fix this issue, please refer to the solution posted here https://github.com/project-sunbird/sunbird-community/discussions/127

**Comment by keshavprasadms** [comment]
Also please post all details like which release, tag etc you are using. Else there is no way we would be able to guess. The 3.4.0 and above tags are updated with this fix - https://github.com/project-sunbird/sunbird-devops/releases/tag/release-3.4.0
