### ISSUE TITLE
Certificate renewal question

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-devops#24]
Question - when an SSL certificate is renewed do we have to update the config file with the new certificate value(s) and rerun `deploy-core.sh` and `deploy-proxy.sh` scripts? 

@kochhar @Manojvv @mathewjpallan @rjshrjndrn

**Comment by rjshrjndrn** [comment]
@bachia, You have to update the groupvars file with SSL, and run `deploy-proxy.sh`.

Regards,
Rajesh

**Comment by bachia** [comment]
Thank you @rjshrjndrn
