### ISSUE TITLE
Issue deploying sunbird-portal

### ISSUE THREAD

**Issue by sunilkamat2018** [project-sunbird/sunbird-devops#261]
I have setup the server setup successfully and my portal works fine. Now we have made changes in sunbird-portal and created the docker image . Trying to deploy the same as player_player microservice on app server.
I have pulled the image on app server:
ubuntu@ip-172-31-34-78:~$ sudo docker images
REPOSITORY                                                    TAG                 IMAGE ID            CREATED             SIZE
5206732006.dkr.ecr.us-east-1.amazonaws.com/sunbird/player   1.9.0-bronze        04592ffcc5f6        3 days ago          1.05GB
5206732006.dkr.ecr.us-east-1.amazonaws.com/sunbird/player   1.8.0-bronze        a16d97eaaed6        3 days ago          1.05GB

Running this command to deploy the service:
ubuntu@ip-172-31-34-78:~/sunbird-devops$ ansible-playbook -i deploy/socio-devops/ansible/inventories/staging/hosts ansible/deploy.yml --tags "stack-sunbird" --extra-vars "hub_org=sunbird image_name=5206732006.dkr.ecr.us-east-1.amazonaws.com/sunbird/player image_tag=1.9.0-bronze service_name=player deploy_stack=True sunbird_api_auth_token=ABC vault_badging_authorization_key=XYZ"
(NOTE: ABC and XYZ are from jwt_token_player.txt and badger_token.txt)

Ansible script runs properly, but container doesn't start!!
I had to rollback the player_player service.

Please help me here . I can provide more details if needed.

**Comment by rjshrjndrn** [comment]
closing the PR due to inactivity
