### ISSUE TITLE
Getting error while running certbot.sh

### ISSUE THREAD

**Issue by Haritest** [project-sunbird/sunbird-devops#29]
Hi Team,

 While running ./certbot.sh script we getting bellow error.

-e This script won't work for aws, as it's black listed in letsencrypt
 so if youre running on aws please press ctrl+c with in 5 seconds
please enter your dns name
sunbird.....io(entered correct Domain name here)
dpkg-query: error: --search needs at least one file name pattern argument

Use --help for help about querying packages.

**Comment by rjshrjndrn** [comment]
sorry for the bug. That's because of dpkg. Fixed the plesae pull the repo.

**Comment by Haritest** [comment]
issue resolved
thank you
