### ISSUE TITLE
Logs are not coming under Kibana.

### ISSUE THREAD

**Issue by manzarul** [project-sunbird/sunbird-devops#30]
Once server is restarted some times logs are visible , but after an hour or two non of the logs are coming , this is happening across all installation.

**Comment by kochhar** [comment]
@manzarul which service is this for? Please give the specific steps to reproduce the problem to help in getting to a solution. 

Take a look at: http://www.sunbird.org/contributions/filing_a_bug/

**Comment by manzarul** [comment]
@kochhar , this is happening with learner-service and actor-service both.

**Comment by SMYALTAMASH** [comment]
This is fixed
