### ISSUE TITLE
Unable to install dbs

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-devops#43]
Facing the following error when trying to execute `sudo ./install-dbs.sh <implementation-name>-devops/ansible/inventories/<environment-name>`

> sluser@sl-dev-dbsrvr:~/sunbird-devops/deploy$ sudo ./install-dbs.sh sldev-devops/ansible/inventories/dev/
> @@@@@@@@@ Elasticsearch installation
> ./install-dbs.sh: 14: ./install-dbs.sh: ansible-playbook: not found

@Manojvv @mathewjpallan @kochhar @rjshrjndrn

**Comment by rjshrjndrn** [comment]
@bachia 

Are you running the script in db instance?

if so, as per our security design, we're not installing anything but dbs in DB instance. So please run the script from the application server.

Regards,
Rajesh

**Comment by bachia** [comment]
thank you @rjshrjndrn 

I am now using the latest scripts.
