### ISSUE TITLE
content_service failed to start

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-devops#44]
content_service_content_service container doesn't start after installation. 

Log messages below:

> content_service_content_service.1.v8uv854olarj@sl-dev-appsrvr    | /home/sunbird/mw/content/node_modules/azure-storage/lib/common/services/servicesettings.js:83
content_service_content_service.1.v8uv854olarj@sl-dev-appsrvr    |         throw new SyntaxError(SR.INVALID_CONNECTION_STRING);
content_service_content_service.1.y20aiss38x01@sl-dev-appsrvr    |         throw new SyntaxError(SR.INVALID_CONNECTION_STRING);
content_service_content_service.1.njvasdcxy1qw@sl-dev-appsrvr    |         throw new SyntaxError(SR.INVALID_CONNECTION_STRING);
content_service_content_service.1.w86oh7jiwxvs@sl-dev-appsrvr    |         throw new SyntaxError(SR.INVALID_CONNECTION_STRING);
content_service_content_service.1.w86oh7jiwxvs@sl-dev-appsrvr    |         ^
content_service_content_service.1.v8uv854olarj@sl-dev-appsrvr    |         ^
content_service_content_service.1.y20aiss38x01@sl-dev-appsrvr    |         ^
content_service_content_service.1.njvasdcxy1qw@sl-dev-appsrvr    |         ^
content_service_content_service.1.njvasdcxy1qw@sl-dev-appsrvr    |
content_service_content_service.1.w86oh7jiwxvs@sl-dev-appsrvr    |
content_service_content_service.1.v8uv854olarj@sl-dev-appsrvr    |
content_service_content_service.1.y20aiss38x01@sl-dev-appsrvr    |
content_service_content_service.1.y20aiss38x01@sl-dev-appsrvr    | SyntaxError: Connection strings must be of the form "key1=value1;key2=value2".
content_service_content_service.1.njvasdcxy1qw@sl-dev-appsrvr    | SyntaxError: Connection strings must be of the form "key1=value1;key2=value2".
content_service_content_service.1.w86oh7jiwxvs@sl-dev-appsrvr    | SyntaxError: Connection strings must be of the form "key1=value1;key2=value2".
content_service_content_service.1.v8uv854olarj@sl-dev-appsrvr    | SyntaxError: Connection strings must be of the form "key1=value1;key2=value2".

![screen shot 2018-02-14 at 12 37 23 pm](https://user-images.githubusercontent.com/2817641/36191573-da111c2e-1183-11e8-9e56-4d1a10bad29d.png)

@Manojvv @harishgilimi @kochhar @rjshrjndrn @mathewjpallan

**Comment by harishgilimi** [comment]
@bachia latest version of content service needs **sunbird_azure_account_name**,  **sunbird_azure_account_key** environment variables to upload QR Code images using Dial codes(new feature) ,another option is you can give environment variables as dummy string,  In this case the QR code storage won't work.

**Comment by bachia** [comment]
Thank you everybody. Setup Azure cloud storage and provided required details. confirmed working.

@Manojvv @harishgilimi @vrayulu
