### ISSUE TITLE
Missing ElasticSearch indexes

### ISSUE THREAD

**Issue by bachia** [project-sunbird/sunbird-devops#46]
Current installation process doesn't create required ElasticSearch indexes. Without these indices creation of organization fails. Please see if this step can be incorporated as part of installation process. 

@Manojvv @kochhar @rjshrjndrn @mathewjpallan

**Comment by Manojvv** [comment]
Automated and added to the installation scripts.  Thanks for informing.

**Comment by Manojvv** [comment]
@bachia Please pull the latest code and run the `./sunbird_install.sh -s dbs` will create the elasticsearch schema .

**Comment by bachia** [comment]
Thank you @Manojvv 

@kochhar @rjshrjndrn @mathewjpallan

**Comment by bachia** [comment]
Confirmed working. Closing this issue.
