### ISSUE TITLE
Upgrade of NGINX

### ISSUE THREAD

**Issue by kochhar** [project-sunbird/sunbird-devops#57]
@Abhishek-Govula commented on [Mon Feb 19 2018](https://github.com/project-sunbird/project-sunbird.github.io/issues/265)

Hi,
  Can you please provide the latest version of NGINX for the proxy service. The current proxy service is using NGINX version# 1.13.3 which is obsolete. 

---

@steotia commented on [Mon Feb 19 2018](https://github.com/project-sunbird/project-sunbird.github.io/issues/265#issuecomment-366612996)

@mathewjpallan can you please get your team to triage it? Or else if it is a configuration which @Abhishek-Govula can handle, let him know how to do it.
cc @Manojvv 

---

@steotia commented on [Mon Feb 19 2018](https://github.com/project-sunbird/project-sunbird.github.io/issues/265#issuecomment-366695191)

How are you deploying the stack?
Let me know the deployment steps (basic).

---

@Abhishek-Govula commented on [Mon Feb 19 2018](https://github.com/project-sunbird/project-sunbird.github.io/issues/265#issuecomment-366700233)

@steotia  - I am running the deployment script. Inside sunbird-devops/deploy/deploy-proxy.sh directory

**Comment by santhosh-optit** [comment]
Provided the latest version of NGINX (v1.13.8) image.
