### ISSUE TITLE
Julia Computing - keycloak not up after Azure server restart

### ISSUE THREAD

**Issue by thillaibirla** [project-sunbird/sunbird-devops#58]
Hi, The julia computing azure servers got restarted early this morning and the sunbird.juliacomputing.io login was not working - we were getting 502 Bad gateway error.

On investigation we found that the keycloak is not up and we needed to manually restart the keycloak to ensure that the sunbird application is up and running.

Raising this issue as part of documentation - @mathewjpallan @rjshrjndrn

**Comment by rjshrjndrn** [comment]
@thillaibirla 
Hi, Sorry that keycloak was not enabled as systemd service, to start at boot. Will be fixed at release-1.5
