### ISSUE TITLE
Steps to configure Sunbird for the aiprohub domain

### ISSUE THREAD

**Issue by thillaibirla** [project-sunbird/sunbird-devops#69]
Hi Team, @rjshrjndrn @mathewjpallan 

We would like to configure the current Julia Computing sunbird installation(sunbird.juliacomputing.io) to  www.aiprohub.org (ip address - 52.224.127.144).  Can you pls list down the steps involved in keycloak and config including the certificate changes required.

thanks,
Thillai.

**Comment by rjshrjndrn** [comment]
Hi, Please follow these following.
use the same branch, which you used for installation.

```
1. update the IP in config

certbot.sh, if you used that to get the SSL, else update the SSL and change the path of certificates in config.

2. ./sunbird_install.sh -s proxy
```

**Comment by Jenifer-Ramsingh** [comment]
@rjshrjndrn 
Hi Rajesh.,

_While creatind DNS we are facing this error_
root@sunbirdcore:/home/sunbird/sunbird_julia/sunbird-devops/deploy# ./certbot.sh 
This script won't work for aws, as it's black listed in letsencrypt
so if youre running on aws please press ctrl+c with in 5 seconds
please enter your dns name : www.aiprohub.org
certbot is already installed
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for www.aiprohub.org
Cleaning up challenges
**Problem binding to port 80: Could not bind to IPv4 or IPv6.**
please inform if any changes need to do from our end

Thanks,
Jenifer Ramingh

**Comment by rjshrjndrn** [comment]
@Jenifer-Ramsingh @thillaibirla 
Please stop docker before updating the certificates
`sudo service docker stop`

**Comment by thillaibirla** [comment]
@rjshrjndrn - thanks Rajesh for the quick inputs, we have configured aiprohub.org for juliacomputing sunbird installation.

Thanks,
Thillai.
