### ISSUE TITLE
Sunbird - upgrade of player to  0.0.10-gold

### ISSUE THREAD

**Issue by thillaibirla** [project-sunbird/sunbird-devops#70]
Hi Team @rjshrjndrn , @mathewjpallan 

As part of a issue resolution, sunbird engg team - @harishgilimi  has asked us to upgrade the player for julia computing sunbird to  0.0.10-gold.  Can you pls list down the steps to upgrade the player.

Thanks
Thillai.

@jenifer-ramsingh - FYI

**Comment by Manojvv** [comment]
Hi,

Currently 0.0.10-gold is not a stable version. Still if you are planning  to use that 0.0.10 player docker image, please follow the below steps.

Steps:
Change the player image version in `sunbird-devops/deploy/deploy-core.sh` from 0.0.9-gold to 0.0.10-gold.
Run the `./sunbird-install.sh -s core `

**Comment by SMYALTAMASH** [comment]
This activity is completed.
