### ISSUE TITLE
Implementation team - API access for "Course Batch Management"

### ISSUE THREAD

**Issue by kaliappanLatitude** [project-sunbird/sunbird-devops#98]
Dear Team,

Please give access to the "Course Batch Management" to the API key which is shared to implementation team.
This is required for release activity which involves these newly introduced APIs.

Thanks & Regards,
Kaliappan G

**Comment by ahghatol** [comment]
API's for course batch 

/course/v1/batch/create   - courseAdmin
/course/v1/batch/update  - courseAdmin
/course/v1/batch/user/add - courseAdmin
/course/v1/batch/read - courseUser
/course/v1/batch/list- courseUser

Whitelist groups

**Comment by manzarul** [comment]
@Jayaprakash8887 please find the course progress api list here : http://www.sunbird.org/apis/courseprogressapi/#tag/Course-Progress-API(s)

**Comment by SMYALTAMASH** [comment]
This activity is completed.
